language: node_js
cache: yarn
dist: bionic

jobs:
  include:
  ## TEST STAGE

  # Test main OSes on Node 10.x branch.
  - os: linux
    node_js: "10.16"
    env: ZMQ_DRAFT=true INCLUDE_COMPAT_TESTS=true

  - os: linux
    env: ALPINE_CHROOT=3.10 ZMQ_DRAFT=true INCLUDE_COMPAT_TESTS=true
    sudo: required

  - os: osx
    env: ZMQ_DRAFT=true
    node_js: "10.16"

  - os: windows
    node_js: "10.16"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: ZMQ_DRAFT=true YARN_GPG=no

  - os: windows
    node_js: "10.16/x86"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: ZMQ_DRAFT=true YARN_GPG=no

  # Test shared libraries on Linux and macOS.
  - os: linux
    node_js: "10.16"
    env: ZMQ_SHARED=true
    addons: {apt: {packages: libzmq3-dev}}

  - os: osx
    node_js: "10.16"
    env: ZMQ_SHARED=true
    addons: {homebrew: {packages: zeromq, update: true}}

  # Test older versions of ZMQ.
  - os: linux
    node_js: "10.16"
    env: ZMQ_VERSION=4.2.4

  # Test recent Node versions.
  - os: linux
    node_js: "12"
    # Skip GC tests due to https://github.com/node-ffi-napi/weak-napi/issues/16
    env: ZMQ_DRAFT=true SKIP_GC_TESTS=true INCLUDE_COMPAT_TESTS=true

  - os: linux
    node_js: "13"
    # Skip GC tests due to https://github.com/node-ffi-napi/weak-napi/issues/16
    env: ZMQ_DRAFT=true SKIP_GC_TESTS=true

  ## PREBUILD STAGE

  - stage: prebuild
    os: linux
    env: ARCHIVE_SUFFIX=-x64
    node_js: "10.16"
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: linux
    env: ALPINE_CHROOT=3.10 ARCHIVE_SUFFIX=-x64-musl
    sudo: required
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: linux
    node_js: "10.16"
    env: ARCH=arm TRIPLE=arm-linux-gnueabihf GCC=8 ARCHIVE_SUFFIX=-armv7
    addons: {apt: {packages: [gcc-8-arm-linux-gnueabihf, g++-8-arm-linux-gnueabihf]}}
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: linux
    node_js: "10.16"
    env: ARCH=arm64 TRIPLE=aarch64-linux-gnu GCC=8 ARCHIVE_SUFFIX=-armv8
    addons: {apt: {packages: [gcc-8-aarch64-linux-gnu, g++-8-aarch64-linux-gnu]}}
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: osx
    node_js: "10.16"
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: windows
    node_js: "10.16"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: YARN_GPG=no ARCHIVE_SUFFIX=-x64
    script: script/ci/prebuild.sh

  - stage: prebuild
    os: windows
    node_js: "10.16/x86"
    # https://travis-ci.community/t/build-doesnt-finish-after-completing-tests/288
    env: YARN_GPG=no ARCHIVE_SUFFIX=-x86
    script: script/ci/prebuild.sh

  ## PUBLISH STAGE

  - stage: publish
    os: linux
    node_js: "10.16"
    env: IGNORE_SCRIPTS=true
    script: script/ci/package.sh

  fast_finish: true
  allow_failures:
  - os: linux
    node_js: "13"

stages:
- name: test
- name: prebuild
  if: tag IS present
- name: publish
  if: tag IS present

install:
- travis_retry script/ci/install.sh

script:
- travis_retry script/ci/test.sh

deploy:
# Deploy prebuilds to Github releases.
- provider: releases
  draft: false
  file: "${TRAVIS_TAG:-latest}-${TRAVIS_OS_NAME}${ARCHIVE_SUFFIX}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_BUILD_STAGE_NAME = Prebuild"
  api_key:
    # Github API token for @zeromqjs-integration
    secure: LGumSW+o+hjoYeYTR0HPSkeonjipv5jdflV0AjzIkgQpZAYQv7tOtKBZDbHTdn1kK/P6Kgu3MpzmOsOD/Wr8tdUEK23u1IgL4oUi+sWxqIz0qpOXRnNo6flxZ71LWOtdRJsx9tM+sGKIcHwgcAzvKLeaILheBFxRyYWajluRvCzGfzpcgM5fBxl/lyhJ6KC5xQYbMVZJSHH0frUeSzs3FIlW2NPYBeRk0BWpsmxcLaNGZt2rPEg2RZszRSk7me+i8Z3QmhcbFwugT1LmnRqnHFG3xt4kndwEMUPmncdmyCO//V+cBHCjkt1T3Y06o6BoGC5hSjZvu5E2msAOlfx3iB9ZBxuVE2av2MEwdGh16sOg7wUYJN/OBHNIn8aevvDyWBfCwxqXCUV+Y4UzDqL01JePjYHTpaUN5v4dD+Pw6g6rUj2B4ImMb54Uum8NikcqODjii1iJqF08wZdrentTOz85eLLclRY3qu5I0dR50DPfZt1sXVgIzBt/jCDADLUlIFmvwFCRn3/wp+//xNFZMFy0LyaxDuVfKnje4lcHSo3/ueIBYvyKh4UwWs2WZwt34rzaABAKzSy+/B2d8cFRo+ov0jiwdIdxIexYAI0GjoA3+gOq6GnscSIxEwtH440Lzu+Deq5A602OZnXY1rnlaxcVG+V2ldmxY6EGOwMdZxc=

# Deploy package including all generated prebuilds to NPM.
- provider: npm
  email: r.w.timmermans@gmail.com
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_BUILD_STAGE_NAME = Publish"
  api_key:
    # NPM API token for @zeromqjs-integration
    secure: sJLxdZXXP0pbUEt2PQkJfraPHqG0jrpoesdVDw189KQvOyeLxRMzuF+BpxGhm6wkrOVF+H4AMVbpTC52yZoHZBLMLUNcHhXjMeztxVsuCe54NLDWSZQ9xGzrZh8npZZCykjdkb+Ax0Xf8wNRcBPZy7KNCoA/JD/qkRyzMjIOQLefxdxAQUcFdYh4sWWc6GqJzxVjX7/Q6jh9l+5Ky+ayLypGaZRirSrsVCsrGhhebPCx9RVQrzopips5fC8UJRF+t3oWRmsrqlsh4FAlo6PPRVzraJL8b92krHrea1wtIPJbTH66sWxzvCw3O8TyiQIkTQwCKVSTmJ4UOVsKchIwWABdno/7DS/5kQyvP/f8yuQ+/kburuRxeJWkTuOz08EAQBviGR5VxVbffPBQyakfEhO0Aw9BC4yGZxTx4mXv2JqSAZRuDS4tntAfpVbkBUZvIDMqGAviMlM9JgTyvoEYmRJAUA33vjaKTa2kJ/bls/lSej6Hl/f5BJ7PHHzofmqi4PPdqRVHX61zrm/TaG5OfIO8wS2cTGFwTWOHcn9BCYzkEm8z+xJ9Kz4dRpKCQAKDCr/FXRAGSyWtA7Wk6T9hdx67wKHOXTRaoiT+V1Ci9xPAUFURJKl/Cef7VOMT1imnx0o3VKlX2md/Up9oSi0tuXHrz+Vol/D+3hMEgVsbub8=

env:
  global:
    # GITHUB_TOKEN=<Github API token for @zeromqjs-integration>
    secure: C4S4sfX6e3VubfxkeM1LA3qbKM1BnhnCLVOgCHiHYeRpnVROMQmXqxo9S0cy+M0oj35jdaGWaCjJjbdpE2ofc/9MMEGeBsT91Gz3cE9HAmwDsp4XD12fxjrK0tTr6Bu/G1gxmUYxNw3Vb0EeaRAMx19MO/vRQTbxlSGf38zNLQccioqPq1ihIHAg9g6K9gtoE/WZnCTvydvOQYnBpBaEsiQJBVmmqZnO6Rxg1t8dxRjyUnzEufdKzPT4Qf1sn6zIC7mM362ndIuE4V483BiK5xt/ZDzkb6QPdgWSnTS2dBc2gCrNMnIAdqY1tbQ9PdDr8phY/X5tYqjZwwL8sRcab5gZm5qTzK1fdz3sYOYDU1j8uUyh7W9H10ePHkwhQgQxZc6g8kkwEq8mA/35dMO+x/VaIYYDUoFW8rU+suVFThuSGZhjCzEwM4+b/BkL26Ux1MrXJdsaqpRqBJNJKO9SyaDBrdNHZ4aYLhvnTikE82PR98mQTO7bPdZbrmMPVa1mE9dl1TOdPCk22ykzJuIMYSaFDDm5fUF3smkBqmkvVE3EO4FoVYyVL5tM4PoZzIQVO9H6w8nli49Ry0zZ0mEuUuEKG+uH4ZY6wL49m/f7WJ3ndnUF8FUHoW1Z43V2SZ+MHtIZX8srQxWmXN38x2hHc9HePN629SHEqx7OV8zFoJU=
