name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  Build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest
        node_version:
          - 14
        node_arch:
          - x64
        zmq_draft:
          - false
        zmq_shared:
          - false
        zmq_version:
          - 4.3.4
        skip_gc_finalizer_tests:
          - true

        # include:
          # - os: windows-latest
          #   node_version: 14
          #   node_arch: x86
          #   zmq_draft: false
          #   zmq_shared: false
          #   skip_gc_finalizer_tests: true

          # - os: macos-11.0
          #   node_version: 15
          #   node_arch: arm64
          #   zmq_draft: false
          #   zmq_shared: false

    env:
      ZMQ_VERSION: ${{ matrix.zmq_version }}
      ZMQ_DRAFT: ${{ matrix.zmq_draft }}
      ZMQ_SHARED: ${{ matrix.zmq_shared }}
      SKIP_GC_FINALIZER_TESTS: ${{ matrix.skip_gc_finalizer_tests }}
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ./node_modules/
            ~/.npm
            ~/AppData/Roaming/npm-cache
            ./build/zeromq-${{ matrix.zmq_version }}.tar.gz
            ./zeromq-${{ matrix.zmq_version }}.tar.gz
            ./libzmq
            ./build/libzmq
          key: "cache-OS:${{ matrix.os }}-arch:${{ matrix.node_arch }}-ZMQ_DRAFT:${{ matrix.zmq_draft }}-ZMQ_VERSION:${{ matrix.zmq_version }}-Node:${{ matrix.node_version }}-${{ hashFiles('./package.json') }}"
          restore-keys: |
            "cache-OS:${{ matrix.os }}-arch:${{ matrix.node_arch }}-ZMQ_DRAFT:${{ matrix.zmq_draft }}-ZMQ_VERSION:${{ matrix.zmq_version }}-Node:${{ matrix.node_version }}"

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.node_arch }}

      - name: Install Mac-OS Dependencies
        if: contains(matrix.os, 'macos')
        run: |
          brew install libsodium

      - uses: ilammy/msvc-dev-cmd@v1
        if: contains(matrix.os, 'windows')
        with:
          arch: ${{ matrix.node_arch }}

      - name: Install Dependencies and Build
        run: npm install

      - name: Prebuild
        run: npm run prebuild
        env:
          ARCH: ${{ matrix.node_arch }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./prebuilds

      - name: Test
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 4
          max_attempts: 3
          command: npm run test

      - name: Lint
        if: contains(matrix.os, 'ubuntu')
        run: npm run lint
